# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ea3d8877226f3e95b03878f00d2d79a"
name = "shopilamCustomApp"
handle = "shopilamcustomapp"
application_url = "https://gets-direct-investor-pixel.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_products,read_customers"

[auth]
redirect_urls = ["https://gets-direct-investor-pixel.trycloudflare.com/auth/callback", "https://gets-direct-investor-pixel.trycloudflare.com/auth/shopify/callback", "https://gets-direct-investor-pixel.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
